### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yiddu** [bunian/tianzigebishun#1]
Warning: file_get_contents(bishun_data/田.json): failed to open stream: No such file or directory in /volume1/web/tianzigebishun/tzg.php on line 105 Warning: count(): Parameter must be an array or an object that implements Countable in /volume1/web/tianzigebishun/tzg.php on line 109
田字格中不显示字，只有田字格

**Comment by bunian** [comment]
请把压缩包解压

**Comment by yiddu** [comment]
> 请把压缩包解压

问题解决，谢谢提供这么好的东西。
