### ISSUE TITLE
请更改一下文案，样式抄袭可以，但是文案也全盘抄袭就不讲武德了

### ISSUE THREAD

**Issue by hyman-ren** [bunian/tianzigebishun#6]
请更改一下文案，样式抄袭可以，但是文案也全盘抄袭就不讲武德了

**Comment by bunian** [comment]
真的不好意思，这是我的问题。
我将会做好以下补救：
1.声明前端来源与作者。
2.修改去除相关文案（可能早期版本或者在其他平台的文件我修改不了，这真是不好意思）。
3.在README.md中进行致歉。

如有必要我会删除当前库。

**Comment by hyman-ren** [comment]
适当模仿我也不反对，但是别把我网站文案全盘抄袭下来，我网站有一定用户基础了，你这样做，会出现很多文案和我一样的李鬼，让我很难和之前用户解释。

**Comment by hyman-ren** [comment]
看了你的致歉信息，感觉非常坦诚，技术不达标不至于，你可以发挥一下你的想象力，多做出一些为用户服务的功能。

**Comment by hyman-ren** [comment]
我在我的项目中推荐了你的项目，如果可以，希望你把这个项目做的更好，但是建议不要盲目的抄袭。
